</head>
	
	<!--START OF PAGE SECTION-->
	<body>
		<div id="wrapper">	

			<!--BANNER SECTION-->
			<div id="masthead" >
				<img class="banner" alt="banner" src="images/love%20it%204.png" />
			</div>

			<!--NAVIGATION SECTION-->
			<div id="nav">
				<a href="index.php" class="nav">Home</a>
				<a href="products.php" class="nav">Products</a>
				<a href="contact.php" class="nav">Contact Us</a>
				<a href="cart.php" class="nav">Cart</a>
			</div>
			<!--CONTENTS SECTION-->
			<div id="content">