	<div id="div1" class="targetdiv">
					<h2 class="title">"Don't even ask!" - Wine Glass</h2>
					<br />
					<table class="hidden">
						<tr>
							<td>
								<img class="photo" src="images/glass.jpg" alt="Wine Glasses"/>
							</td>
							<td>
								<p class="hidinfo"> Come Pick up a couple of these amazing wine glasses! 
								 They make a perfect gift for a Whiny friend or family member. Start seeing the glass half full!</p>
							</td>
						</tr>
						<tr>
							<td>
								<label class="hidinfo" id="price">$4.99 each</label>	
							</td>
							<td>&nbsp;</td>
						</tr>
					</table>
				</div>
						
				<div id="div2" class="targetdiv">
					<h2 class="title">Hot Pink Flamingo</h2>
					<br />
					<table class="hidden">
						<tr>
							<td>
								<img class="photo" src="images/bird.jpg" alt="Garden Flamingo"/>
							</td>
							<td>
								<p class="hidinfo">looking for the perfect lawn decoration?
								Your garden will be the talk of the town with your new pizazzy pink flamingo. </p>
							</td>
						</tr>
						<tr>
							<td>
								<label class="hidinfo">$10 each</label>	
							</td>
							<td>&nbsp;</td>
						</tr>
					</table>
				</div>
							
				<div id="div3" class="targetdiv">	
					<h2 class="title">Jewellery</h2>
					<br />
					<table class="hidden">
						<tr>
							<td>
								<img class="photo" src="images/jewel.jpg" alt="Jewellery"/>
							</td>
							<td>
								<p class="hidinfo">Show your partner you care by buying them some stylish new bangles, rings and necklaces! </p>
							</td>
						</tr>
						<tr>
							<td>
								<label class="hidinfo">$14 each</label>					
							</td>
							<td>&nbsp;</td>
						</tr>
					</table>
				</div>
							
				<div id="div4" class="targetdiv">
					<h2 class="title">Potted Plants</h2>
					<br />				
					<table class="hidden">
						<tr>
							<td>
								<img class="photo" src="images/plant.jpg" alt="Potted Plants"/>
							</td>
							<td>
								<p class="hidinfo">Come take a look at the assortment of 
								plants we have to offer! They're sure to Leaf a good Impression.</p>
							</td>
						</tr>
						<tr>
							<td>
								<label class="hidinfo">$20 each</label>			
							</td>
							<td>&nbsp;</td>
						</tr>
					</table>
				</div>
							
				<div id="div5" class="targetdiv">	
					<h2 class="title">Fabric and Materials</h2>
					<br />				
					<table class="hidden">
						<tr>
							<td>
								<img class="photo" src="images/cloth.jpg" alt="Fabrics"/>
							</td>
							<td>
								<p class="hidinfo">Come check out our wide range of fabrics and materials! 
								Order more than 10 square metres and receive a 10% discount</p>
							</td>
						</tr>
						<tr>
							<td>
								<label class="hidinfo">$5 p/m</label>
							</td>
							<td>&nbsp;</td>
						</tr>
					</table>
				</div>
							
				<div id="div6" class="targetdiv">	
					<h2 class="title">Home Decore</h2>
					<br />
					<table class="hidden">
					<tr>
						<td>
							<img class="photo" src="images/ring.jpg" alt="Decore"/>
						</td>
						<td>
							<p class="hidinfo">Be a good friend, look out for him by giving him a life-saver ring.
							Note: Item made of wood, decoration only!</p>
						</td>
					</tr>
					<tr>
						<td>
								<label class="hidinfo">$149 each</label>	
						</td>
						<td>&nbsp;</td>
					</tr>
					</table>
				</div>		
			</div>